---
    - name: Ensure the webupd8 launchpad apt repository key is present
      retries: 3
      delay: 2
      register: result
      until: result is succeeded
      apt_key:
        id: EEA14886
        keyserver: keyserver.ubuntu.com
        state: present
      become: yes

    - name: Add PPA for Oracle java
      apt_repository:
        repo: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main'
        update_cache: yes
      tags: java
      become: yes

    - name: Accept Oracle license
      tags: java
      debconf:
        name: oracle-java8-installer
        question: shared/accepted-oracle-license-v1-1
        value: 'true'
        vtype: select
      become: yes

    - name: Install Oracle java
      retries: 3
      delay: 2
      register: result
      until: result is succeeded
      become: yes
      apt:
        update_cache: yes
        install_recommends: yes
        pkg:
          - oracle-java8-installer